version: '3'

services: 
    redis-server:
        image: 'redis'
    node-app:
        restart: always
        build: . # look current location for existing Dockerfile
        ports: 
            - "4001:8081"  # localmachine : container port
        
